version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elastic
    ports:
      - ${ES_PORT}:9200
      - ${ES_PORT2}:9300
    environment:
      bootstrap.memory_lock : true
      discovery.type : single-node
      ELASTIC_PASSWORD : ${ELASTIC_PASSWORD}
      xpack.security.enabled : ${ELASTIC_SECURITY}
      ES_JAVA_OPTS: "-Xms256m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana
    depends_on: [elasticsearch]
    links: [elasticsearch]
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:${ES_PORT}
      ELASTICSEARCH_USERNAME: ${ELASTIC_USERNAME}
      ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}

  oracle:
    image: gvenzl/oracle-xe:21.3.0
    container_name: oracle-xe
    ports:
      - ${ORACLE_PORT}:1521
    environment:
      - ORACLE_DATABASE=oraDB
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
      - TARGET_PDB=oraDB
    volumes:
      - './scripts/oracle/1_create_user.sql:/container-entrypoint-initdb.d/1_create_user.sql'
      - './scripts/oracle/2_call_tmp.sh:/container-entrypoint-initdb.d/2_call_tmp.sh'
      - './scripts/oracle/3_create_tables.sql:/tmp/3_create_tables.sql'
      - './scripts/oracle/4_insert_data.sql:/tmp/4_insert_data.sql'