ALTER SESSION SET CONTAINER=oraDB;

CREATE USER oraUser IDENTIFIED BY oraUser123;
GRANT ALL PRIVILEGES TO oraUser;

CREATE USER OWNERAPP IDENTIFIED BY OWNERAPP123;
GRANT ALL PRIVILEGES TO OWNERAPP;

COMMIT;