ALTER SESSION SET CURRENT_SCHEMA=OWNERAPP;

CREATE TABLE TB_GENRE (
    "ID"    NUMBER(12) NOT NULL,
    "NAME"  VARCHAR2(30) NOT NULL,
    PRIMARY KEY (ID)
);
COMMENT ON COLUMN TB_GENRE.ID IS 'Identificador do gênero';
COMMENT ON COLUMN TB_GENRE.NAME IS 'Nome do gênero';

CREATE TABLE TB_MOVIE (
    "ID"        NUMBER(12) NOT NULL,
    "TITLE"     VARCHAR2(50) NOT NULL,
    "YEAR"      NUMBER(4),
    PRIMARY KEY (ID)
);
COMMENT ON COLUMN TB_MOVIE.ID IS 'Identificaçao da Tabela de Filmes';
COMMENT ON COLUMN TB_MOVIE.TITLE IS 'Título do Filme';
COMMENT ON COLUMN TB_MOVIE.YEAR IS 'Ano do Filme';

CREATE TABLE TB_GENRE_MOVIE(
    GENRE_ID NUMBER NOT NULL,
    MOVIE_ID NUMBER NOT NULL
);
COMMENT ON COLUMN TB_GENRE_MOVIE.GENRE_ID IS 'Identificador de gênero';
COMMENT ON COLUMN TB_GENRE_MOVIE.MOVIE_ID IS 'Identificador do filme';

ALTER TABLE TB_GENRE_MOVIE ADD CONSTRAINT FK_GENRE FOREIGN KEY (GENRE_ID) REFERENCES TB_GENRE (ID);
ALTER TABLE TB_GENRE_MOVIE ADD CONSTRAINT FK_MOVIE FOREIGN KEY (MOVIE_ID) REFERENCES TB_MOVIE (ID);

CREATE SEQUENCE SEQGENRE START WITH 1 INCREMENT BY 1 NOCACHE ORDER;
CREATE SEQUENCE SEQMOVIE START WITH 1 INCREMENT BY 1 NOCACHE ORDER;

COMMIT;