ALTER SESSION SET CURRENT_SCHEMA=OWNERAPP;

INSERT ALL
    INTO TB_GENRE VALUES (1, 'Comedy')
    INTO TB_GENRE VALUES (2, 'Sci-Fi')
    INTO TB_GENRE VALUES (3, 'Terror')
SELECT 1 FROM DUAL;

INSERT ALL
    INTO TB_MOVIE VALUES (1, 'Spaceballs', 1990)
    INTO TB_MOVIE VALUES (2, 'Sexta-Feira 13', 1980)
SELECT 1 FROM DUAL;

INSERT ALL
    INTO TB_GENRE_MOVIE VALUES (1, 1)
    INTO TB_GENRE_MOVIE VALUES (2, 1)
    INTO TB_GENRE_MOVIE VALUES (3, 2)
SELECT 1 FROM DUAL;

COMMIT;